services:
  memo.backendoptim.listener.data_container:
    class:  Memo\BackendOptimBundle\EventListener\DataContainerListener
    public: true
    arguments:
      - "@database_connection"
      - "@contao.intl.locales"
      - "@monolog.logger.contao"
      - "@?terminal42_node.permission_checker"
      - "@request_stack"
      - "@?codefog_tags.manager.terminal42_node"
